import { error } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { verifyUrlSignature } from '$lib/services/r2-storage';
import { getEnv } from '$lib/server/env';

/**
 * GET /api/audio/serve?key=...&expires=...&sig=...
 *
 * Serves audio from R2 using a signed URL. The signed URL is generated by
 * `R2StorageService.getSignedUrl()` which produces an HMAC signature over
 * the object key and expiry timestamp.
 *
 * No session is required — the signature itself is the auth token.
 */
export const GET: RequestHandler = async (event) => {
	const { url } = event;
	const env = getEnv(event);

	const key = url.searchParams.get('key');
	const expiresStr = url.searchParams.get('expires');
	const sig = url.searchParams.get('sig');

	if (!key || !expiresStr || !sig) {
		error(400, { message: 'Missing required query parameters: key, expires, sig.' });
	}

	const expiresAt = Number(expiresStr);
	if (!Number.isFinite(expiresAt)) {
		error(400, { message: 'Invalid expires parameter.' });
	}

	const signingSecret = env.R2_SIGNING_SECRET;
	if (!signingSecret) {
		error(500, { message: 'Server signing secret not configured.' });
	}

	const valid = await verifyUrlSignature(signingSecret, key, expiresAt, sig);
	if (!valid) {
		error(403, { message: 'Invalid or expired signature.' });
	}

	// Access R2 bucket binding
	const bucket = env.AUDIO_BUCKET;
	if (!bucket) {
		error(503, {
			message:
				'Audio storage not available. In local development, ensure wrangler dev is running with R2 bindings configured.'
		});
	}

	const object = await bucket.get(key);
	if (!object) {
		error(404, { message: 'Audio object not found in storage.' });
	}

	const contentType = object.httpMetadata?.contentType ?? 'audio/mpeg';
	const body = await object.arrayBuffer();

	return new Response(body, {
		status: 200,
		headers: {
			'Content-Type': contentType,
			'Cache-Control': 'private, max-age=3600',
			'Accept-Ranges': 'bytes',
			'Content-Length': String(body.byteLength)
		}
	});
};
